---
  - name: install the various packages we require
    dnf:
      name:
        - gvim
        - vim-airline # TODO - fork to personal github and pull from there instead?
        - fontconfig
        - ShellCheck
        - ctags
        - global-ctags
        - git
        - tmux
        - gron # make json grepable in line oriented manner
        - discount # provides the 'markdown' program that will convert markdown > html
      state: latest

  - name: make vim directory
    file:
      path: "{{ homedir }}/.vim"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make syntax directory
    file:
      path: "{{ homedir }}/.vim/syntax"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make pack directory
    file:
      path: "{{ homedir }}/.vim/pack"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make my-plugins directory
    file:
      path: "{{ homedir }}/.vim/pack/my-plugins"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make start directory
    file:
      path: "{{ homedir }}/.vim/pack/my-plugins/start"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make colors directory
    file:
      path: "{{ homedir }}/.vim/colors"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make fonts directory
    file:
      path: "{{ homedir }}/.fonts"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make config directory
    file:
      path: "{{ homedir }}/.config"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make fontconfig directory
    file:
      path: "{{ homedir }}/.config/fontconfig"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: make conf.d directory
    file:
      path: "{{ homedir }}/.config/fontconfig/conf.d"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0700

  - name: copy powerline-symbols.conf
    copy:
        src: fonts/10-powerline-symbols.conf
        dest: "{{ homedir }}/.config/fontconfig/conf.d/10-powerline-symbols.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

  - name: copy patched fonts
    copy:
        src: fonts/PowerlineSymbols.otf
        dest: "{{ homedir }}/.fonts/PowerlineSymbols.otf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
    notify: reload fontcache

  - name: copy vimrc
    copy:
        src: vimrc
        dest: "{{ homedir }}/.vimrc"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
    notify: cleanup viminfo

  - name: copy tmux config
    copy:
        src: tmux.conf
        dest: "{{ homedir }}/.tmux.conf"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

  - name: copy solarized
    copy:
        src: colors/solarized.vim
        dest: "{{ homedir }}/.vim/colors/solarized.vim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

  - name: copy django syntax file
    copy:
        src: syntax/django.vim
        dest: "{{ homedir }}/.vim/syntax/django.vim"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

  - name: gitgutter plugin
    git:
      repo: 'https://github.com/dushankw/vim-gitgutter.git'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-gitgutter"
      version: master
    notify: fix permissions on plugins

  - name: commentary plugin
    git:
      repo: 'https://github.com/dushankw/vim-commentary'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-commentary"
      version: master
    notify: fix permissions on plugins

  - name: surround plugin
    git:
      repo: 'https://github.com/dushankw/vim-surround'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-surround"
      version: master
    notify: fix permissions on plugins

  - name: indexed search plugin
    git:
      repo: 'https://github.com/dushankw/vim-indexed-search'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-indexed-search"
      version: master
    notify: fix permissions on plugins

  - name: super tab plugin
    git:
      repo: 'https://github.com/dushankw/supertab'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/supertab"
      version: master
    notify: fix permissions on plugins

  - name: AutoComplPop plugin
    git:
      repo: 'https://github.com/dushankw/AutoComplPop'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/AutoComplPop"
      version: master
    notify: fix permissions on plugins

  - name: vim json plugin
    git:
      repo: 'https://github.com/dushankw/vim-json'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-json"
      version: master
    notify: fix permissions on plugins

  - name: autopairs plugin (must load before endwise)
    git:
      repo: 'https://github.com/dushankw/auto-pairs'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/auto-pairs"
      version: master
    notify: fix permissions on plugins

  - name: gnupg.vim plugin
    git:
      repo: 'https://github.com/dushankw/vim-gnupg.git'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-gnupg"
      version: master
    notify: fix permissions on plugins

  - name: locate.vim plugin
    git:
      repo: 'https://github.com/dushankw/locate.vim.git'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/locate.vim"
      version: master
    notify: fix permissions on plugins

  - name: fugitive plugin
    git:
      repo: 'https://github.com/dushankw/vim-fugitive.git'
      dest: "{{ homedir }}/.vim/pack/my-plugins/start/vim-fugitive"
      version: master
    notify: fix permissions on plugins

# ruby syntax file from vim-ruby
# https://github.com/dushankw/vim-endwise
# https://github.com/vim-scripts/L9
# https://github.com/vim-scripts/taglist.vim
# https://github.com/tpope/vim-git
